### ISSUE TITLE
libc++abi: terminating due to uncaught exception of type std::bad_any_cast: bad any cast

### ISSUE THREAD

**Issue by btc** [ankane/or-tools-ruby#59]
> libc++abi: terminating due to uncaught exception of type std::bad_any_cast: bad any cast

I see this error on occasion. e.g. [here](https://github.com/ankane/or-tools-ruby/actions/runs/8668513847/job/23773722137)

I'm wondering if you have an idea of what causes it? It's not a big deal, as a retry usually addresses the issue. Yet, I'm curious.

Thanks again for creating this wrapper. We are making good use of it.

**Comment by ankane** [comment]
Thanks. The thread backtrace from Crash Reports would be most helpful.

**Comment by cfranklin11** [comment]
I've run into this error as well, so far only in specs running in our CI, but I was able to recreate it, and capture and log the core dump using [logbt](https://github.com/mapbox/logbt).

Gem info:
```
GEM
  remote: https://rubygems.org/
  specs:
    or-tools (0.11.1)
      rice (>= 4.1)
```

The code was running in a Docker container from an image based on the `ruby:3.2-bullseye` image (as far as I can tell, we don't do anything with the C++ version or compiler, so whatever is the default for Debian bullseye should apply). I've attached the output from logbt below. Let me know if you prefer a different format (with explicit instructions for how to generate it, because C++ is well beyond my ken) or need a reproducible example to tinker with.

[or-tools-core-dump.txt](https://github.com/ankane/or-tools-ruby/files/15493537/or-tools-core-dump.txt)

**Comment by ankane** [comment]
@cfranklin11 Thanks for sharing. Unfortunately, I'm still having trouble finding the exact issue.

I was also able to get a crash report locally, but it's for a different spot.

```text
Rice::detail::NativeFunction<operations_research::sat::BoolVar, operations_research::sat::BoolVar (operations_research::sat::BoolVar::*)() const, true>* Rice::detail::NativeRegistry::lookup<Rice::detail::NativeFunction<operations_research::sat::BoolVar, operations_research::sat::BoolVar (operations_research::sat::BoolVar::*)() const, true>*>(unsigned long, unsigned long)
```

**Comment by cfranklin11** [comment]
I've been looking into this off and on as time permits in order to send you a minimal reproducible example, but I've gotten stuck. Every time I try to simplify some of the code from my work codebase, it fails to trigger the `std::bad_any_cast` error. Since I can only get the error in the context of a Rails app running Rspec tests that exercise our optimizer module exactly as written, I'm chalking this up to being an extreme edge case and am looking into ways to work around it.

For anyone else who runs into this error, I was able to narrow down the cause to be, at least in part, due to having the `georuby` and `dbf` gems installed (I have no idea what the mechanism is for this, but the results of my experiments were consistent). `georuby` is an abandoned project, with a viable alternative, so my work-around is to just replace it with a gem that's still maintained. So, one thing for others to try is gradually deleting gems from their codebases to see if the `std::bad_any_cast` stops appearing, because some other gem is interacting with `or-tools` in a way the raises this error.

**Comment by ankane** [comment]
@btc and @cfranklin11 What `ORTools` model / solver classes are you using?

Just found and fixed a memory issue in `RoutingModel`: e0b9f3b66df91b52f878c0d5a7d927fcb36be56e

**Comment by cfranklin11** [comment]
I'm using a `GLOP` solver for a linear optimization problem.

**Comment by ankane** [comment]
Removed the C++ wrapper for `LinearExpr` (as it's not needed) in the commit above, which seems to have fixed CI (still not able to reproduce it locally). This also removes inheritance between Ruby and C++ classes, which could be part of the cause.

**Comment by ankane** [comment]
Found the likely cause (I believe it's an issue in Rice that happens randomly based on hash collisions). Will loop back once it's addressed.

**Comment by ankane** [comment]
If you use Rice from GitHub, the errors should stop (see the PR above). Will push a new version of OR-Tools that requires the fixed version once it's released.
